# permissions for end users to view daemons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daemon-viewer-role
rules:
- apiGroups:
  - lotus.filecoin.io
  resources:
  - daemons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lotus.filecoin.io
  resources:
  - daemons/status
  verbs:
  - get
