
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - lotus.filecoin.io
  resources:
  - daemons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lotus.filecoin.io
  resources:
  - daemons/finalizers
  verbs:
  - update
- apiGroups:
  - lotus.filecoin.io
  resources:
  - daemons/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lotus.filecoin.io
  resources:
  - miners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lotus.filecoin.io
  resources:
  - miners/finalizers
  verbs:
  - update
- apiGroups:
  - lotus.filecoin.io
  resources:
  - miners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lotus.filecoin.io
  resources:
  - wallets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lotus.filecoin.io
  resources:
  - wallets/finalizers
  verbs:
  - update
- apiGroups:
  - lotus.filecoin.io
  resources:
  - wallets/status
  verbs:
  - get
  - patch
  - update
